export const progressTrackerItems = [
  {
    studentName: "AIDEN ANDREWS",
    projectsCompleted: "4/15 Projects Completed",
    taskComplete: [
      { id: 1, isComplete: true },
      { id: 2, isComplete: false },
      { id: 3, isComplete: true },
      { id: 4, isComplete: true },
      { id: 5, isComplete: false },
      { id: 6, isComplete: true },
      { id: 7, isComplete: false },
      { id: 8, isComplete: true },
      { id: 9, isComplete: true },
      { id: 10, isComplete: false },
      { id: 11, isComplete: true },
      { id: 12, isComplete: true },
      { id: 13, isComplete: false },
      { id: 14, isComplete: true },
      { id: 15, isComplete: true },
    ],
  },

  {
    studentName: "COURTNEY BRISTOL",
    projectsCompleted: "1/15 Projects Completed",
    taskComplete: [
      { id: 1, isComplete: true },
      { id: 2, isComplete: true },
      { id: 3, isComplete: true },
      { id: 4, isComplete: true },
      { id: 5, isComplete: true },
      { id: 6, isComplete: true },
      { id: 7, isComplete: true },
      { id: 8, isComplete: false },
      { id: 9, isComplete: false },
      { id: 10, isComplete: false },
      { id: 11, isComplete: false },
      { id: 12, isComplete: false },
      { id: 13, isComplete: false },
      { id: 14, isComplete: false },
      { id: 15, isComplete: false },
    ],
  },
  {
    studentName: "NAGINI CORTES",
    projectsCompleted: "4/15 Projects Completed",
    taskComplete: [
      { id: 1, isComplete: true },
      { id: 2, isComplete: false },
      { id: 3, isComplete: false },
      { id: 4, isComplete: false },
      { id: 5, isComplete: false },
      { id: 6, isComplete: true },
      { id: 7, isComplete: false },
      { id: 8, isComplete: true },
      { id: 9, isComplete: true },
      { id: 10, isComplete: true },
      { id: 11, isComplete: true },
      { id: 12, isComplete: true },
      { id: 13, isComplete: false },
      { id: 14, isComplete: false },
      { id: 15, isComplete: false },
    ],
  },

  {
    studentName: "RAWIRI",
    projectsCompleted: "7/15 Projects Completed",
    taskComplete: [
      { id: 1, isComplete: true },
      { id: 2, isComplete: false },
      { id: 3, isComplete: true },
      { id: 4, isComplete: false },
      { id: 5, isComplete: false },
      { id: 6, isComplete: true },
      { id: 7, isComplete: false },
      { id: 8, isComplete: true },
      { id: 9, isComplete: true },
      { id: 10, isComplete: false },
      { id: 11, isComplete: true },
      { id: 12, isComplete: false },
      { id: 13, isComplete: false },
      { id: 14, isComplete: false },
      { id: 15, isComplete: true },
    ],
  },
];
